// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProdutoEstoqueApi.Context;

#nullable disable

namespace ProdutoEstoqueApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230301175335_fifthMigrationCOrrected2")]
    partial class fifthMigrationCOrrected2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProdutoEstoqueApi.Models.ItemEstoque", b =>
                {
                    b.Property<int>("ItemEstoqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemEstoqueId"));

                    b.Property<int?>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("ItemEstoqueId");

                    b.HasIndex("LojaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItemEstoques");
                });

            modelBuilder.Entity("ProdutoEstoqueApi.Models.Loja", b =>
                {
                    b.Property<int>("LojaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LojaId"));

                    b.Property<string>("Endereco")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Nome")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("LojaId");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("ProdutoEstoqueApi.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ProdutoEstoqueApi.Models.ItemEstoque", b =>
                {
                    b.HasOne("ProdutoEstoqueApi.Models.Loja", "Loja")
                        .WithMany("ItemEstoques")
                        .HasForeignKey("LojaId");

                    b.HasOne("ProdutoEstoqueApi.Models.Produto", "Produto")
                        .WithMany("ItemEstoques")
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Loja");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ProdutoEstoqueApi.Models.Loja", b =>
                {
                    b.Navigation("ItemEstoques");
                });

            modelBuilder.Entity("ProdutoEstoqueApi.Models.Produto", b =>
                {
                    b.Navigation("ItemEstoques");
                });
#pragma warning restore 612, 618
        }
    }
}
