// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProdutoEstoqueApi.Context;

#nullable disable

namespace ProdutoEstoqueApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProdutoEstoqueApi.Models.ItemEstoque", b =>
                {
                    b.Property<int>("ItemEstoqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemEstoqueId"));

                    b.Property<string>("Nome")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ItemEstoqueId");

                    b.ToTable("ItemEstoques");
                });

            modelBuilder.Entity("ProdutoEstoqueApi.Models.Loja", b =>
                {
                    b.Property<int>("LojaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LojaId"));

                    b.Property<string>("Endereco")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("ItemEstoqueId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("LojaId");

                    b.HasIndex("ItemEstoqueId");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("ProdutoEstoqueApi.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Estoque")
                        .HasColumnType("real");

                    b.Property<int?>("ItemEstoqueId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("Preco")
                        .IsRequired()
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ProdutoId");

                    b.HasIndex("ItemEstoqueId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ProdutoEstoqueApi.Models.Loja", b =>
                {
                    b.HasOne("ProdutoEstoqueApi.Models.ItemEstoque", "ItemEstoque")
                        .WithMany("Lojas")
                        .HasForeignKey("ItemEstoqueId");

                    b.Navigation("ItemEstoque");
                });

            modelBuilder.Entity("ProdutoEstoqueApi.Models.Produto", b =>
                {
                    b.HasOne("ProdutoEstoqueApi.Models.ItemEstoque", null)
                        .WithMany("Produtos")
                        .HasForeignKey("ItemEstoqueId");
                });

            modelBuilder.Entity("ProdutoEstoqueApi.Models.ItemEstoque", b =>
                {
                    b.Navigation("Lojas");

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
